CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "skill_types" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "skill_types_name_unique" on "skill_types" ("name");
CREATE UNIQUE INDEX "skill_types_slug_unique" on "skill_types" ("slug");
CREATE TABLE IF NOT EXISTS "companies" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "positions" ("id" integer primary key autoincrement not null, "company_id" integer not null, "title" varchar not null, "start_date" date not null, "end_date" date, "created_at" datetime, "updated_at" datetime, foreign key("company_id") references "companies"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "position_skill" ("id" integer primary key autoincrement not null, "position_id" integer not null, "skill_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("position_id") references "positions"("id") on delete cascade, foreign key("skill_id") references "skills"("id") on delete cascade);
CREATE UNIQUE INDEX "position_skill_position_id_skill_id_unique" on "position_skill" ("position_id", "skill_id");
CREATE TABLE IF NOT EXISTS "icons" ("id" integer primary key autoincrement not null, "icon_type" varchar not null default 'fa', "icon_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "icons_icon_type_icon_name_unique" on "icons" ("icon_type", "icon_name");
CREATE TABLE IF NOT EXISTS "tech_stack_items" ("id" integer primary key autoincrement not null, "skill_id" integer, "name" varchar not null, "percent" integer, "active" tinyint(1) not null default ('0'), "order" integer not null default ('0'), "created_at" datetime, "updated_at" datetime, "icon_id" integer, foreign key("skill_id") references skills("id") on delete set null on update no action, foreign key("icon_id") references "icons"("id") on delete set null);
CREATE INDEX "tech_stack_items_order_index" on "tech_stack_items" ("order");
CREATE TABLE IF NOT EXISTS "skills" ("id" integer primary key autoincrement not null, "skill_type_id" integer not null, "name" varchar not null, "order" integer not null default ('0'), "created_at" datetime, "updated_at" datetime, "icon_id" integer, foreign key("skill_type_id") references skill_types("id") on delete cascade on update no action, foreign key("icon_id") references "icons"("id") on delete set null);
CREATE INDEX "skills_skill_type_id_order_index" on "skills" ("skill_type_id", "order");
